---
- name: Create a virtual machine from a template
  hosts: localhost
  collections:
    - community.vmware
  become: false
  gather_facts: false
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: create folder
      vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state:  present
    -  name: clone VM
       vmware_guest:
         hostname: "{{ vcenter_hostname }}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         validate_certs: no
         datacenter: "{{ vcenter_datacenter }}"
         cluster: "{{ vcenter_cluster }}"
         name: "{{ vm_name }}"
         folder: "{{ vcenter_destination_folder }}"
         template: "{{ vm_template }}"
         state: poweredon
    -  name: Pause for 5Minutes to build app cache
       ansible.builtin.pause:
           seconds: 35
