---
- name: deploy vm from template
  hosts: localhost
  collections:
    - community.vmware
  become: false
  gather_facts: true
  pre_task:
    - include_vars: vars.yml
  tasks:
    - name: create folder
      vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        folder: "{{ vcenter_destination_folder }}"
        state:  poweredon
    - name: Pause for 5Minutes to build app cache
      ansible.builtin.pause:
          seconds: 35
