---
- name: static ip assigning
  hosts: localhost
  become: yes
  collections:
    - community.general
    - ansible.netcommon
  tasks:
    - name: Set new IP address using nmcli module
      community.general.nmcli:
        conn_name: ens192
