---
- name: static ip assigning
  hosts:  10.0.5.156
  become: yes
  tasks:
 #- name: Set new IP address
    - name: Set new IP address using nmcli command
        ansible.builtin.shell:nmcli con show 
        register:nmcli_output
    # ansible.builtin.nmcli:
    #  conn_name: ens192
    #  ifname: ens192
    #  type: ethernet
    #  ipv4: "{{ vm_ip }}/16"
    #  gw4:  10.0.0.2
    #  state: present
 # - name: restart vlan interfaces
 #   command: bash -c  "ifdown ens192  ifup ens192"
