---
- name: Set new IP address without using nmcli module
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Run nmcli con show command
      ansible.builtin.shell:
        cmd: nmcli con show {{ ifname }}
      register: nmcli_output

    - debug:
        var: nmcli_output.stdout_lines

    - name: Set new IP address using shell command
      ansible.builtin.shell:
        cmd: nmcli con mod {{ ifname }} ipv4.address {{ vm_ip }}/16 ipv4.gateway 10.0.0.2

    - name: Restart vlan interfaces
      ansible.builtin.shell:
        cmd: nmcli conn down {{ ifname }} && nmcli conn up {{ ifname }}
