---
- name: Set new IP address without using nmcli module
  hosts: 10.0.7.245
  become: yes
  tasks:
    - name: Run nmcli con show command
      ansible.builtin.shell:
        cmd: nmcli con show ens192
      register: nmcli_output

    - debug:
        var: nmcli_output.stdout_lines

    - name: Set new IP address using shell command
      ansible.builtin.shell:
        cmd: nmcli con mod ens192 ipv4.address 10.0.7.246/16 ipv4.gateway 10.0.0.2

    - name: Restart vlan interfaces
      ansible.builtin.shell:
        cmd: bash -c "ifdown ens192 && ifup ens192"
