- name: static ip assigning
  hosts: "{{ hosts }}"
  become: yes
  tasks:

  - name: Set new IP address
    community.general.nmcli:
      conn_name: "{{ ifname }}"
      ifname: "{{ ifname }}"
      type: ethernet
      ip4: "{{ vm_ip }}/16"
      gw4:  10.0.0.2
      state: present
  
  - name: change ip interfaces
     cmd: nmcli conn down {{ ifname }} ; nmcli conn up {{ ifname }}
     state: present

  - name: restart nmcli service
     cmd: nmcli device reapply {{ ifname }}
     state: down
     ignore_errors: true
     delegate_to: 10.0.7.241
