---
- name: static ip assigning
  hosts: "{{ hosts }}"
  become: yes
  collections:
  - community.general
  - ansible.netcommon
  tasks:
  - name: Set new IP address
    nmcli:
      conn_name: {{ ifname }}
      ifname: {{ ifname }}
      type: ethernet
      ipv4: "{{ vm_ip }}/16"
      gw4:  10.0.0.2
      state: present
  - name: restart vlan interfaces
    command: bash -c  "ifdown {{ ifname }}  ifup {{ ifname }}"
