---
- hosts: 10.0.7.245
  become: yes
  tasks:

  - name: install needed network manager libs
    yum:
      name: '{{ item }}'
      state: installed
    with_items:
      - NetworkManager-glib
      - libnm-qt-devel.x86_64
      - nm-connection-editor.x86_64
      - libsemanage-python
      - policycoreutils-python

- name: static ip assigning
  tasks:
  - name: Set new IP address
  - nmcli:
      conn_name: ens192
      ifname: ens192
      type: ethernet
      ip4: "{{ vm_ip }}/16"
      gw4: 10.0.0.2
      state: present
  - name: restart vlan interfaces
    command: bash -c  "ifdown ens192  ifup ens192"
