- name: static ip assigning
  hosts: "{{ hosts }}"
  become: yes
  tasks:

  - name: Set new IP address
    community.general.nmcli:
      conn_name: "{{ ifname }}"
      ifname: "{{ ifname }}"
      type: ethernet
      ip4: "{{ vm_ip }}/16"
      gw4:  10.0.0.2
      state: present
  - name: restart vlan interfaces
    command: bash -c  "nmcli down {{ ifname }}  nmcli up {{ ifname }}"
