---
- name: static ip assigning
  hosts:  localhost
  become: yes
  collections:
  - community.general
  - ansible.netcommon
  tasks:
 #- name: Set new IP address
  - name: Set new IP address using nmcli command
      command: nmcli con show ens192
      register: nmcli_output
    # ansible.builtin.nmcli:
    #  conn_name: ens192
    #  ifname: ens192
    #  type: ethernet
    #  ipv4: "{{ vm_ip }}/16"
    #  gw4:  10.0.0.2
    #  state: present
 # - name: restart vlan interfaces
 #   command: bash -c  "ifdown ens192  ifup ens192"
