---
- name: install needed network manager libs
  package:
    name:
      - NetworkManager-glib
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present
- name: static ip assigning
  hosts: 10.0.7.245
  become: yes
  collections:
  - community.general
  - ansible.netcommon
  tasks:
  - name: Set new IP address
    nmcli:
      conn_name: ens192
      ifname: ens192
      type: ethernet
      ipv4: "{{ vm_ip }}/16"
      gw4:  10.0.0.2
      state: present
  - name: restart vlan interfaces
    command: bash -c  "ifdown ens192  ifup ens192"
