---
- name: static ip assigning
  hosts:  10.0.5.156
  become: yes
  tasks:
 #- name: Set new IP address
    - name: Set new IP address using nmcli command
      ansible.builtin.shell: nmcli con show
      register: nmcli_output
