---
- hosts: all
  become: yes
  tasks:
    - name: Kullanıcı Ekle
      user:
        name: pardus
        password: "$6$Hw5kMc7sajWMmYvY$av9018zEIyGLbBKoGgAl3Zj1GBkDpkHJm77Mxw07b765R/B17uQcHxqoGGJIjvirBclzgJJpzl3FOYV/GuX6u/"
        comment: Pardus Kullanıcısı
        shell: "/bin/bash"
        groups: sudo
        append: yes
        state: present
        create_home: yes
