---
- hosts: all
  become: yes
  tasks:
    - name: Create a virtual machine from a template
	community.vmware.vmware_guest:
		hostname: "{{ vcenter_hostname }}"
		username: "{{ vcenter_username }}"
		password: "{{ vcenter_password }}"
		folder: /deployed_vm
		name: testvm_2
		state: poweredon
		template: Template_Windows_SRV2022_Local
		disk:
		- size_gb: 60
		type: thin
		datastore: VxRail-Virtual-SAN-Datastore-67966368-ff9e-4875-9f72-ad5aef3e42a3
		# Add another disk from an existing VMDK
		- filename: "[datastore1] testvms/testvm_2_1/testvm_2_1.vmdk"
		hardware:
		memory_mb: 4096
		num_cpus: 4
		num_cpu_cores_per_socket: 2
		scsi: paravirtual
		memory_reservation_lock: true
		mem_limit: 8096
		mem_reservation: 4096
		cpu_shares_level: "high"
		mem_shares_level: "high"
		cpu_limit: 8096
		cpu_reservation: 4096
		max_connections: 5
		hotadd_cpu: true
		hotremove_cpu: true
		hotadd_memory: false
		version: 12 # Hardware version of virtual machine
		boot_firmware: "efi"
		cdrom:
			- controller_number: 0
			unit_number: 0
			state: present
			type: iso
			iso_path: "[datastore1] livecd.iso"
		networks:
		- name: VM Network
		mac: aa:bb:dd:aa:00:14
		wait_for_ip_address: true
	delegate_to: localhost
	register: deploy
