---
- name: Create a virtual machine from a template
  hosts: localhost
  collections:
    - community.vmware
  become: false
  gather_facts: false
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: Clone a VM from Template and customize
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        folder: "{{ vcenter_destination_folder }}"
        hardware:
          memory_mb: "{{ vm_memory | default(2048) }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
        - name: VM Network
          ip: "{{ ip_address }}"
          netmask: "{{ netmask }}"
          gateway: "{{ gateway }}"
          domain: ozon.com.tr
          dns_servers:
          - 10.0.0.10
          - 10.0.0.1
        customization:
          autologon: yes
          dns_servers:
          - 10.0.0.10
          - 10.0.0.1
          domain: ozon.com.tr
          password: new_vm_password
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
