---
- name: Create a virtual machine add Disk
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: Add disks to vm
      vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs:  "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        disk:
          - size_gb: "{{ vm_disk_gb | int }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
            state: present
            scsi_controller: "{{ vm_disk_scsi_controller | int }}"
            unit_number: "{{ vm_disk_scsi_unit | int }}"
            scsi_type: "{{ vm_disk_scsi_type }}"
            disk_mode: "{{ vm_disk_mode }}"
      - name: Connect to windows host and expand the drive
        ansible.windows.win_powershell:
          script: |
            # Variable specifying the drive you want to extend
            $drive_letter = "C"
            # Script to get the partition sizes and then resize the volume
            $size = (Get-PartitionSupportedSize -DriveLetter $drive_letter)
            Resize-Partition -DriveLetter $drive_letter -Size $size.SizeMax
